name: Environmnet Variable on

on: push
env: 
  WF_ENV: Accessible across all the jobs within the on
  ENCRPTED_ENV: ${{ secrets.ENCRPTED_ENV }}
  
jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV_VAR: Available within the job kind
    steps:
      - name: Log my env variable
        env: 
          STEP_ENV_VAR: Available within the step
        run: | 
          echo "WF_ENV: ${ENCRPTED_ENV}"
          echo "JOB_ENV: ${JOB_ENV_VAR}"  
          echo "STEP1_ENV: ${STEP_ENV_VAR}"
      - name: Second step
        run: |
          echo "WF_ENV: ${ENCRPTED_ENV}"
          echo "JOB_ENV: ${JOB_ENV_VAR}"  
          echo "STEP1_ENV: ${STEP_ENV_VAR}"
      - name: default var
        run: |
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV_VAR}"
          echo "ENCRYPT_ENV: ${ENCRPTED_ENV}"
          echo "Workflow Number: ${{ github.run_number}}"
          echo "Runner Run ID: ${{ github.run_id }}"
